blog:
  uploadPath: D:\neon_workspace\.metadata\.plugins\org.eclipse.wst.server.core\tmp0\wtpwebapps\upload\
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/manage
    username: root
    password: 123
  redis:
    host: 127.0.0.1
    port: 6379